# First remove *all* keybindings
unbind-key -a
# Now reinsert all the regular tmux keys
# bind ^X lock-server
bind ^C new-window -c "$HOME"
bind c new-window -c "#{pane_current_path}"
bind ^D detach
bind * list-clients

bind H previous-window
bind L next-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind 1 select-window -t 1
bind 2 select-window -t 2
bind 3 select-window -t 3
bind 4 select-window -t 4
bind 5 select-window -t 5
bind 6 select-window -t 6
bind 7 select-window -t 7
bind 8 select-window -t 8
bind 9 select-window -t 9
bind 0 select-window -t 10

bind [ copy-mode
bind ] paste-buffer
bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind z resize-pane -Z
bind ^L refresh-client
bind l refresh-client
bind | split-window
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind '"' choose-window
bind -r Left select-pane -L
bind -r Down select-pane -D
bind -r Up select-pane -U
bind -r Right select-pane -R
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7
bind : command-prompt
bind * setw synchronize-panes
# idk what this does
# bind P set pane-border-status
bind x kill-pane
# bind x swap-pane -D
bind S choose-session
bind R source-file ~/.config/tmux/tmux.conf
bind K send-keys "clear"\; send-keys "Enter"

bind-key -T copy-mode-vi v send-keys -X begin-selection
# use the system clipboard
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'




bind -r g popup -w 90% -h 80% -E -d '#{pane_current_path}' lazygit

